import { Lock, ShieldCheck, FileCheck2, Server } from 'lucide-react'

const items = [
  {
    icon: Lock,
    title: 'PCI-compliant payments',
    body: 'Card and BACS Direct Debit flows are handled by Stripe Checkout. We never see or store card data.',
  },
  {
    icon: ShieldCheck,
    title: 'Signed, offline-capable licences',
    body: 'Each licence is a RS256 JWT validated locally — no phone-home, safe for air-gapped networks.',
  },
  {
    icon: FileCheck2,
    title: 'Auditable invoices',
    body: 'Invoices generated by Stripe are downloadable as PDFs and archived in your account.',
  },
  {
    icon: Server,
    title: 'Procurement-friendly',
    body: 'Pay by card, BACS or bank transfer via invoice. VAT handled automatically for UK / EU customers.',
  },
]

export function TrustBadges() {
  return (
    <div id="trust" className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
      {items.map(({ icon: Icon, title, body }) => (
        <div key={title} className="rounded-xl border bg-card p-5">
          <Icon className="mb-3 size-5 text-primary" aria-hidden />
          <div className="font-medium text-foreground">{title}</div>
          <p className="mt-1 text-sm text-muted-foreground">{body}</p>
        </div>
      ))}
    </div>
  )
}
